<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Serveur <small>Page de création d'un Serveur</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-rocket"></i>
                <a href="<?= $this->url("profond/default", array("controller" => "Machine")) ?>">Machine</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Création</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->