<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Serveur <small>Page de création d'un Serveur</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-rocket"></i>
                <a href="<?= $this->url("profond/default", array("controller" => "Machine")) ?>">Machine</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="#">Création</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->


<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-briefcase"></i>Ajout d'une Machine SSH
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form action="<?= $this->url("profond/default", array("controller" => "Machine", "action" => "addssh")) ?>" method="POST" class="form-horizontal">
                    <div class="form-body">
                        <div class="form-group">
                            <label class="col-md-3 control-label">Nom de la machine :</label>
                            <div class="col-md-4">
                                <input name="<?= $this->formAddSshMachine->get("label")->getName() ?>" type="text" class="form-control" placeholder="Nom de la Machine" value="<?php echo $this->formAddSshMachine->get("label")->getValue() ?>">
                                <span class="help-block">
                                    Attention seulement ces caractères sont utilisable [a-zA-Z0-9]</span>
                                <?php foreach ($this->formAddSshMachine->getMessages("label") as $err): ?>
                                    <span class="help-block">
                                        <?= $err ?>
                                    </span>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Adresse Ip de la Machine :</label>
                            <div class="col-md-4">
                                <input name="<?= $this->formAddSshMachine->get("ip")->getName() ?>" type="text" class="form-control" placeholder="Adresse IP" value="<?php echo $this->formAddSshMachine->get("ip")->getValue() ?>">
                                <span class="help-block">
                                    Format accepté : X.X.X.X (ipv4) ou X:X:X:X:X:X (ipv6)</span>
                                <?php foreach ($this->formAddSshMachine->getMessages("ip") as $err): ?>
                                    <span class="help-block">
                                        <?= $err ?>
                                    </span>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Utilisateur SSH :</label>
                            <div class="col-md-4">
                                <input name="<?= $this->formAddSshMachine->get("username")->getName() ?>" type="text" class="form-control" placeholder="Utilisateur SSH" value="<?php echo $this->formAddSshMachine->get("username")->getValue() ?>">
                                <span class="help-block">
                                    </span>
                                <?php foreach ($this->formAddSshMachine->getMessages("username") as $err): ?>
                                    <span class="help-block">
                                        <?= $err ?>
                                    </span>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Password SSH :</label>
                            <div class="col-md-4">
                                <input name="<?= $this->formAddSshMachine->get("password")->getName() ?>" type="password" class="form-control" placeholder="Password SSH" value="<?php echo $this->formAddSshMachine->get("password")->getValue() ?>">
                                <span class="help-block">
                                    </span>
                                <?php foreach ($this->formAddSshMachine->getMessages("password") as $err): ?>
                                    <span class="help-block">
                                        <?= $err ?>
                                    </span>
                                <?php endforeach; ?>
                            </div>
                        </div>

                    </div>
                    <input type="hidden" name="<?php echo $this->formAddSshMachine->get("token_csrf")->getName() ?>" value="<?php echo $this->formAddSshMachine->get("token_csrf")->getValue() ?>" />
                    <div class="form-actions fluid">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn blue">Ajouter</button>
                            <button onclick="document.location = '<?= $this->url("profond/default", array("controller" => "Machine")) ?>';" type="button" class="btn default">Annuler</button>
                        </div>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>