                   
<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Serveurs <small>Listing des Serveurs accessibles</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li class="btn-group">
                <a style="color: white;" href="<?= $this->url("profond/default", array("controller" => "Machine", "action" => "addssh")) ?>" type="button" class="btn blue">
                    <span>Ajouter</span><i class="fa fa-plus"></i>
                </a>
            </li>
            <li>
                <i class="fa fa-rocket"></i>
                <a href="<?= $this->url("profond/default", array("controller" => "Machine")) ?>">Serveurs</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<!-- ................ -->

<div class="row">
    <?php foreach ($this->Machines as $Machine): ?>
        <?php
        $color = "";
        if ($Machine->getReady()) {
            $color = "green";
        } else {
            if ($Machine->getInstallIncomming()) {
                $color = "grey-silver";
            } else {
                $color = "grey-silver";
            }
        }
        ?>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="dashboard-stat <?= $color ?>">
                <div class="visual">
                    <i class="fa fa-cloud"></i>
                </div>
                <div class="details">
                    <div class="number">
                        <?=
                            $Machine->getLabel()
                        ?>
                    </div>
                    <div class="desc">
                        <?php if($Machine->getConnectionType() == "SSH"): ?>
                            <?= $Machine->getConfig()["ip"] ?> : <?= $Machine->getConfig()["username"] ?><br/>
                        <?php else: ?>

                        <?php endif; ?>
                    </div>
                </div>
                <a class="more" href="#">
                    Détails - LastPing : <?= $Machine->getLastPing()->format(DATE_RFC1036) ?> <i class="m-icon-swapright m-icon-white"></i>
                </a>
            </div>
        </div>
    <?php endforeach; ?>

</div>
<!-- ................ -->
<!-- END PAGE CONTENT-->