<!-- BEGIN LOGIN FORM -->
<form class="login-form" action="/login" method="post">
    <h2 class="form-title">Profond UI - version 4</h2>
    <h3 class="form-title">Authentification</h3>
    <div class="alert alert-danger display-hide">
        <button class="close" data-close="alert"></button>
        <span>
            Entre votre email et password. </span>
    </div>
    <?php if (isset($this->error)): ?>
        <div class="alert alert-danger">
            <strong>Attention!</strong> <?= $this->error ?>
        </div>
    <?php endif; ?>
    <?php
    if (count($this->form_login->getMessages("email")) > 0) {
        $emailW = "has-warning";
    } else {
        $emailW = "";
    }
    ?>
    <div class="form-group <?= $emailW ?>">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9">Email</label>
        <div class="input-icon <?= $emailW ?>">
            <i class="fa fa-envelope"></i>
            <input class="form-control placeholder-no-fix" type="email" autocomplete="off" placeholder="Email" name="email"
                   <?php if (isset($this->form_login)): ?> value="<?php echo $this->form_login->get("email")->getValue() ?>"  <?php endif; ?>
                   />
        </div>
    </div>
    <?php
    if (count($this->form_login->getMessages("password")) > 0) {
        $passwordW = "has-warning";
    } else {
        $passwordW = "";
    }
    ?>
    <div class="form-group <?= $passwordW ?>">
        <label class="control-label visible-ie8 visible-ie9">Password</label>
        <div class="input-icon <?= $passwordW ?>">
            <i class="fa fa-lock"></i>
            <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Password" name="password"/>
        </div>
        <?php foreach ($this->form_login->getMessages("password") as $err): ?>
            <span class="help-block">
                <?= $err ?>
            </span>
        <?php endforeach; ?>
    </div>

    <input type="hidden" name="<?php echo $this->form_login->get("token_csrf")->getName() ?>" value="<?php echo $this->form_login->get("token_csrf")->getValue() ?>" />
    <div class="form-actions">
        <label class="checkbox">
            <!-- <input type="checkbox" name="remember" value="1"/> Se Souvenir de moi --></label> 
        <button type="submit" class="btn green pull-right">
            Login <i class="m-icon-swapright m-icon-white"></i>
        </button>
    </div>
    <div class="forget-password">
        <h4>Vous avez perdu votre mot de passe ?</h4>
        <p>
            Aucune inquiétude, cliquez <a href="javascript:;" id="forget-password">
                ici </a>
            pour ré-initialiser votre mot de passe.
        </p>
    </div>
    <div class="create-account">
        <p>
            Vous n'avez pas encore de compte ?&nbsp; <a href="javascript:;" id="register-btn">
                Créer un compte </a>
        </p>
    </div>
</form>
<!-- END LOGIN FORM -->

<!-- BEGIN FORGOT PASSWORD FORM -->
<form class="forget-form" action="index.html" method="post">
    <h3>Mot de Passe perdu ?</h3>
    <p>
        Entrer votre email pour ré-initialiser votre mot de passe.
    </p>
    <div class="form-group">
        <div class="input-icon">
            <i class="fa fa-envelope"></i>
            <input class="form-control placeholder-no-fix" type="text" autocomplete="off" placeholder="Email" name="email"/>
        </div>
    </div>
    <div class="form-actions">
        <button type="button" id="back-btn" class="btn">
            <i class="m-icon-swapleft"></i> Retour </button>
        <button type="submit" class="btn green pull-right">
            Envoyer <i class="m-icon-swapright m-icon-white"></i>
        </button>
    </div>
</form>
<!-- END FORGOT PASSWORD FORM -->

<!-- BEGIN REGISTRATION FORM -->
<form class="register-form" action="index.html" method="post">
    <h3>Inscription</h3>
    <p>
        Entrer vos détails personnels:
    </p>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Nom Complet</label>
        <div class="input-icon">
            <i class="fa fa-font"></i>
            <input class="form-control placeholder-no-fix" type="text" placeholder="Nom Complet" name="fullname"/>
        </div>
    </div>
    <div class="form-group">
        <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
        <label class="control-label visible-ie8 visible-ie9">Email</label>
        <div class="input-icon">
            <i class="fa fa-envelope"></i>
            <input class="form-control placeholder-no-fix" type="text" placeholder="Email" name="email"/>
        </div>
    </div>
    <p>
        Entrer vos détails de compte:
    </p>

    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Password</label>
        <div class="input-icon">
            <i class="fa fa-lock"></i>
            <input class="form-control placeholder-no-fix" type="password" autocomplete="off" id="register_password" placeholder="Password" name="password"/>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label visible-ie8 visible-ie9">Re-taper votre Password</label>
        <div class="controls">
            <div class="input-icon">
                <i class="fa fa-check"></i>
                <input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="Re-taper votre Password" name="rpassword"/>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>
            <input type="checkbox" name="tnc"/> I agree to the <a href="#">
                Terms of Service </a>
            and <a href="#">
                Privacy Policy </a>
        </label>
        <div id="register_tnc_error">
        </div>
    </div>
    <div class="form-actions">
        <button id="register-back-btn" type="button" class="btn">
            <i class="m-icon-swapleft"></i> Retour </button>
        <button type="submit" id="register-submit-btn" class="btn green pull-right">
            Inscription <i class="m-icon-swapright m-icon-white"></i>
        </button>
    </div>
</form>
<!-- END REGISTRATION FORM -->