<!-- BEGIN PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PAGE TITLE & BREADCRUMB-->
        <h3 class="page-title">
            Projet <small>Erreur</small>
        </h3>
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <i class="fa fa-briefcase"></i>
                <a href="<?= $this->url("profond/default", array("controller" => "Project")) ?>">Projet</a>
            </li>
        </ul>
        <!-- END PAGE TITLE & BREADCRUMB-->
    </div>
</div>
<!-- END PAGE HEADER-->

<div class="note note-success">
    <h4 class="block">Ok !</h4>
    <p>
        <?= $this->message ?>
    </p>
</div>