<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu" data-auto-scroll="true" data-slide-speed="200">
            <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
            <li class="sidebar-toggler-wrapper" style="margin-bottom: 3px;">
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler">
                </div>
                <!-- END SIDEBAR TOGGLER BUTTON -->
            </li>
            <li class="start <?php if ($this->ControllerName() == "Profond\Controller\Index"): ?> active <?php endif ?>">
                <a href="<?= $this->url("profond") ?>">
                    <i class="icon-home"></i>
                    <span class="title">Accueil</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="<?php if ($this->ControllerName() == "Profond\Controller\Executable"): ?> active <?php endif ?>">
                <a href="<?= $this->url("profond/default", array("controller" => "Executable")) ?>">
                    <i class='icon-fire'></i>
                    <span class="title">Executables</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="<?php if ($this->ControllerName() == "Profond\Controller\Job"): ?> active <?php endif ?>">
                <a href="<?= $this->url("profond/default", array("controller" => "Job")) ?>">
                    <i class='icon-fire'></i>
                    <span class="title">Job</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="<?php if ($this->ControllerName() == "Profond\Controller\Machine"): ?> active <?php endif ?>">
                <a href="<?= $this->url("profond/default", array("controller" => "Machine")) ?>">
                    <i class="icon-rocket"></i>
                    <span class="title">Calculateurs</span>
                    <span class="selected"></span>
                </a>
            </li>

            <li class="<?php if ($this->ControllerName() == "Profond\Controller\Project"): ?> active <?php endif ?>">
                <a href="<?= $this->url("profond/default", array("controller" => "Project")) ?>">
                    <i class='icon-briefcase'></i>
                    <span class="title">Projets</span>
                    <span class="selected"></span>
                </a>
            </li>

            <li class="<?php if ($this->ControllerName() == "Profond\Controller\Historique"): ?> active <?php endif ?>">
                <a href="<?= $this->url("profond/default", array("controller" => "Historique")) ?>">
                    <i class='icon-list'></i>
                    <span class="title">Historiques</span>
                    <span class="selected"></span>
                </a>
            </li>

            <li class="<?php if ($this->ControllerName() == "Profond\Controller\Admin"): ?> active <?php endif ?>">
                <a href="<?= $this->url("profond/default", array("controller" => "Admin")) ?>">
                    <i class='icon-users'></i>
                    <span class="title">Utilisateurs</span>
                    <span class="selected"></span>
                </a>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
</div>
<!-- END SIDEBAR -->